### PR TITLE
SPICE updates & branch merge (+ added TRIFIC)

### PR DESCRIPTION
**Pull request by jsmallcombe**
I've been through and manually merged in the various unpushed changes I had.
Everything seems to be working as it should now for SPICE.

In the spirit of moving away from histograms I have cleaned out all the other detector's histogram related functions in the EventAction that werent being used by anything.
If we can add the x,y,z & Px Py Pz of the primary generator to the ntuple then somewhere down the line we can update the SPICE codes and remove the histograms entirely.

I have also added the geometry for the TRIFIC detector, though this doesnt work well at the moment as (unsurprisingly) the physics list isnt optimised for high energy high energy heavy ions.

Only thing you might disagree with, in the PrimaryGenerator I changed some things so the various /DetSys/gun can be used with an ion for decay etc.

### CODE REVIEW

**Comment by VinzenzBildstein** [comment]
This all looks reasonable, but it seems you've accidentally included a TRIFIC header file inside the src folder?

**Comment by VinzenzBildstein** [comment]
Oh, and I will open up a separate issue to discuss changes to the ntuple tree.

**Comment by jsmallcombe** [comment]
Removed the misplaced duplicate file.

**Comment by VinzenzBildstein** [comment]
Thanks!

**Pull request merged**
